import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../app/styles/tailwind.css'
import { Layout } from './components/Layout'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex h-full bg-zinc-50 dark:bg-black">
        <Providers>
          <div className="flex w-full">
            <Layout>
              {children}
            </Layout>
          </div>
        </Providers>
      </body>
    </html>
  )
}
